/*
TASK 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

const int N = 4000000;
long long int mem[N];

long long int evenFib(int n)
{
	long long int s = 1;
	mem[0] = mem[1] = 1;

	for (size_t i = 2; i <= n; i++)
	{
		mem[i] = mem[i - 1] + mem[i - 2];
		if (!(mem[i] & 1)) s += mem[i];
	}
	return s;
}

int main()
{
	std::cout << evenFib(N) << '\n';
}